version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: shoyu-db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data/"
    restart: unless-stopped

volumes:
  postgres:
    name: bun-postgres